import Layout from '../components/Layout';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { SocialIcon } from 'react-social-icons';

export default function Home(this: any) {
    return (
        <>
            <Head>
				<title>Rateria Poli-USP</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo-fundo-azul.svg" />
			</Head>
            <Layout currentPage="Home">
                
            </Layout>
        </>
    )
}