import Layout from '../components/Layout';
import Head from 'next/head';
import styles from '../styles/Repertory.module.css';
import { SocialIcon } from 'react-social-icons';

export default function Contacts() {
	return (
		<>
			<Head>
				<title>Rateria Poli-USP</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo-fundo-azul.svg" />
			</Head>

			<Layout currentPage="Repertory">
				<div className={styles.contentWrapper}>
					<div className={styles.sectionTitle}>
						<div className={styles.titleLine}></div>
					</div>

					<div className={styles.wrapper}>
						<h1 className={styles.title}>Repertório</h1>
						<div className={styles.container}></div>
					</div>
				</div>
			</Layout>
		</>
	);
}
